# Generated by Django 5.2.5 on 2025-09-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название аниме')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='season_posters/')),
                ('type', models.CharField(choices=[('season', 'Сезон'), ('movie', 'Фильм')], default='season', max_length=10)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='main.anime')),
            ],
            options={
                'unique_together': {('anime', 'number', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер серии')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название серии')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.season')),
            ],
            options={
                'unique_together': {('season', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название озвучки')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceovers', to='main.episode')),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео файл')),
                ('voiceover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='main.voiceover')),
            ],
            options={
                'unique_together': {('voiceover',)},
            },
        ),
    ]
